Repository Virtual-Royaume/Royaume-Discord-Bot, pull requests merged in 2023-04, with the labels that each got.

#188 Correction d'une erreur qui se produit quand on essaie d'éditer la réponse d'une interaction après 15 minutes
  src/commands/inactive/inactive.cmd.ts
Labels: bug

#200 Meilleure dénomination des fonctions
  src/utils/function.ts
  src/utils/handler/command/command.ts
Labels: update

#193 Ajout de logs pour chaque commandes, events et actions divers
  src/commands/anniversaire/[sub-commands]/set.cmd.ts
  src/commands/clean/clean.cmd.ts
  src/commands/emoji/emoji.cmd.ts
  src/commands/forum/[sub-commands]/rename.cmd.ts
  src/commands/forum/[sub-commands]/resolve.cmd.ts
  src/commands/inactive/inactive.cmd.ts
  src/commands/interaction/[sub-commands]/verif.cmd.ts
  src/commands/main/[sub-commands]/group-add/add-channel.cmd.ts
  src/commands/main/[sub-commands]/group-add/add-role.cmd.ts
  src/commands/main/[sub-commands]/group-remove/remove-channel.cmd.ts
  src/commands/main/[sub-commands]/group-remove/remove-role.cmd.ts
  src/commands/member/member.cmd.ts
  src/commands/stats/stats.cmd.ts
  src/commands/top-message/[sub-commands]/channel.cmd.ts
  src/commands/top-message/[sub-commands]/month.cmd.ts
  src/commands/top-message/[sub-commands]/total.cmd.ts
  src/commands/top-voice/[sub-commands]/month.cmd.ts
  src/commands/top-voice/[sub-commands]/total.cmd.ts
  src/events/channel-delete/channel-delete.event.ts
  src/events/github-link-reaction/github-link-reaction.event.ts
  src/events/guild-member-add/guild-member-add.event.ts
  src/events/guild-member-remove/guild-member-remove.event.ts
  src/events/message-create/message-create.event.ts
  src/events/message-link-reaction/message-link-reaction.event.ts
  src/events/role-delete/role-delete.event.ts
  src/events/roles-selector/roles-selector.event.ts
  src/events/roulette/roulette.event.ts
  src/events/user-update/user-update.event.ts
  src/events/verif-message-reaction-add/verif-message-reaction-add.event.ts
  src/events/verif-modal/verif-modal.event.ts
  src/tasks/activity-update/activity-update.task.ts
  src/tasks/birthday-checker/birthday-checker.task.ts
  src/tasks/tier-update-game/tier-update-game.task.ts
  src/tasks/tier-update/tier-update.task.ts
  src/tasks/verify-members/verify-members.task.ts
  src/utils/handler/command/command.ts
  src/utils/user.ts
Labels: enhancement

#203 Ajout des versions preview de Discord dans la regex de récupération de lien pour `message-link-reaction`
  src/events/message-link-reaction/message-link-reaction.const.ts
Labels: refactor

#205 Le nombre de message envoyé lors du dépassement d'un certain cap s'affichera à nouveau
  src/events/message-create/message-create.event.ts
Labels: bug

#207 Correction d'un crash avec la function `gqlRequest()` lorsque l'API GraphQL renvoie une erreur qui n'est pas au format JSON
  src/utils/request/request.ts
Labels: bug
