Repository Virtual-Royaume/Royaume-Discord-Bot, pull requests merged in 2023-01, with the labels that each got.

#150 ✏️ Amélioration du texte
  resources/config/messages.json
Labels: refactor

#132 Remove AXIOS
  README.md
  src/utils/request/request.ts
Labels: refactor

#141 🔋 Mise à jour de `/inactive`
  resources/config/messages.json
  src/commands/list/Inactive.ts
Labels: refactor

#142 🖼️ Ajout d'une bannière au `/member`
  src/commands/list/Member.ts
Labels: update

#144 🌙 Ajout d'un mode sombre au graphique des statistiques
  resources/config/messages.json
  src/commands/list/Stats.ts
Labels: refactor

#139 🛡️ Désactivation de certaines fonctionnalités en mode développement
  src/commands/Command.ts
  src/commands/CommandManager.ts
  src/commands/list/Ask.ts
  src/commands/list/Birthday.ts
  src/commands/list/Clean.ts
  src/commands/list/Emoji.ts
  src/commands/list/Forum.ts
  src/commands/list/Inactive.ts
  src/commands/list/Interaction.ts
  src/commands/list/Main.ts
  src/commands/list/Member.ts
  src/commands/list/Presence.ts
  src/commands/list/Role.ts
  src/commands/list/Roulette.ts
  src/commands/list/Stats.ts
  src/commands/list/TopMessage.ts
  src/commands/list/TopVoice.ts
  src/commands/list/WatchTogether.ts
  src/events/Event.ts
  src/events/EventManager.ts
  src/events/list/ChannelDelete.ts
  src/events/list/GithubLinkReaction.ts
  src/events/list/GuildMemberAdd.ts
  src/events/list/GuildMemberRemove.ts
  src/events/list/GuildMemberUpdate.ts
  src/events/list/MessageCreate.ts
  src/events/list/MessageLinkReaction.ts
  src/events/list/Ready.ts
  src/events/list/RoleDelete.ts
  src/events/list/RolesSelector.ts
  src/events/list/RouletteModal.ts
  src/events/list/UserUpdate.ts
  src/events/list/VerifMessageReactionAdd.ts
  src/events/list/VerifModal.ts
  src/tasks/Task.ts
  src/tasks/TaskManager.ts
  src/tasks/list/ActivityUpdate.ts
  src/tasks/list/BirthdaysChecker.ts
  src/tasks/list/ChannelManager.ts
  src/tasks/list/PresenceUpdate.ts
  src/tasks/list/TierUpdate.ts
  src/tasks/list/VerifyMembers.ts
Labels: refactor

#137 🗑️ Suppression de la comande `/watch-together` vu que natif sur Discord
  resources/config/app-integration.json
  resources/config/messages.json
  src/commands/list/WatchTogether.ts
Labels: update

#165 Suppression de la commande `/watch-together` car cette fonctionnalité est maintenant disponible nativement sur Discord
  package.json
Labels: update

#159 Lors de la création d'un post dans un salon forum, un message est envoyé avec une liste des posts similaires
  resources/config/messages.json
  src/events/list/ForumSearch.ts
Labels: enhancement

#157 La commande `/forum resolve` épingle maintenant le message de résolution du post
  src/commands/list/Forum.ts
Labels: update

#169 Mise en place d'un Dockerfile pour avoir une meilleur gestion de l'environnement Railway
  Dockerfile
Labels: enhancement

#167 Correction de divers bugs avec à la commande `/inactive`
  .gitignore
  gql-codegen.ts
  package.json
  resources/config/interaction-ids.json
  resources/config/messages.json
  src/commands/list/Forum.ts
  src/commands/list/Inactive.ts
  src/utils/request/graphql/fragment-masking.ts
  src/utils/request/graphql/gql.ts
  src/utils/request/graphql/index.ts
Labels: bug
